### ISSUE TITLE
Build error while installing terraformer-geostore-leveldb

### ISSUE THREAD

**Issue by davidbeers** [Esri/terraformer-geostore#18]
Terraformer looks great. Unfortunately, with "terraformer-geostore-leveldb": "~1.1.1" included in my package.json dependencies I get the following native build error when running `npm install`:

```
leveldown.target.mk:121: recipe for target 'Release/obj.target/leveldown/src/batch.o' failed
make: *** [Release/obj.target/leveldown/src/batch.o] Error 1
make: Leaving directory '/home/dbeers/Dev/DrivelineScripts/orderedlanes/node_modules/leveldown/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/dbeers/.nvm/versions/node/v11.9.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:197:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
gyp ERR! System Linux 4.15.0-50-generic
gyp ERR! command "/home/dbeers/.nvm/versions/node/v11.9.0/bin/node" "/home/dbeers/.nvm/versions/node/v11.9.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/dbeers/Dev/DrivelineScripts/orderedlanes/node_modules/leveldown
gyp ERR! node -v v11.9.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
```
Build environment:
Ubuntu 18.04.2 LTS
node v11.9.0
node-gyp v3.8.0

**Comment by davidbeers** [comment]
Wait... is LevelStore even supported?  I see docs for it on terraformer.io [here](http://terraformer.io/geostore/#using-in-nodejs) but there's an open issue in terraformer-geostore-memory (from 2014!) that states that LevelStore is no more: https://github.com/Esri/terraformer-geostore-memory/issues/3

**Comment by jgravois** [comment]
Terraformer hasn't really been under active development for several years. the original maintainers all have their hands full with other fun stuff these days.

because of this, i proposed awhile back that the scope of the project be whittled down to just the parsers and spatial predicates.

https://github.com/Esri/terraformer/issues/268

that said, you can find https://github.com/JerrySievert/terraformer-geostore-leveldb here, and pull requests are welcome in _any_ terraformer repository. 

if you're hoping you can log a bug and have it resolved by someone else, i wouldn't hold your breath. 😄

**Comment by jgravois** [comment]
ps: you'd probably have more luck compiling on a (far) older version of Node.js
